# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffcbe0f79a6a3a3675ef23880bba1c944b2f73c687e87654718f2c8b8b74379d2a20f591267639ffab3135bacf5766530d4fb1c1ca1ed488a8729d093c1ad518

test:
  secret_key_base: b23649108f2d92636f9807cba925b2d10e766eb909ee731503ac4f74a5aeca13a1007c690ff5654b4d521ad29b2f75f7a5081655462bc45f6a78205d23008b0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
